"""``--emit-gate-config`` — turn scan results into a diplomat-gate config.

Model to follow: ``registry.py``'s ``generate()`` (stdlib-only, hand-written
YAML, no PyYAML dependency). All category -> policy-family logic lives in
``gate_mapping.GATE_FAMILY_MAP`` (GATE A2); this module only renders it.

Design choices, made explicit rather than left implicit:
  - Generated policies default to ``on_fail: REVIEW``, never ``STOP`` — a
    freshly generated config must not be able to block a real workflow on
    its first run.
  - A category with no implemented policy family is never silently dropped:
    it is rendered as a commented block naming its call sites and the
    diplomat-gate tracking issue, so the config is honest about what it does
    *not* protect yet.
  - No policy id is ever invented: only ids already present in
    ``GateFamily.suggested`` (locked against diplomat-gate's real policy ids
    by ``tests/test_gate_mapping.py``) are emitted.
"""

from __future__ import annotations

import datetime
from io import StringIO
from pathlib import Path

from diplomat_agent import __version__
from diplomat_agent.models import ScanResult
from diplomat_agent.reporter.gate_mapping import GATE_FAMILY_MAP

_MAX_CALL_SITES_SHOWN = 5


def _detected_call_sites(result: ScanResult) -> dict[str, list[tuple[str, int, str]]]:
    """category -> [(file, line, tool_name), ...], one entry per detected side effect."""
    sites: dict[str, list[tuple[str, int, str]]] = {}
    for tool in result.tools:
        for effect in tool.side_effects:
            sites.setdefault(effect.category, []).append((effect.file, effect.line, tool.name))
    return sites


def generate(result: ScanResult, output_path: str | Path, scanned_path: str = ".") -> str:
    """Generate a diplomat-gate config from scan results.

    Writes ``output_path`` and returns the generated YAML content.
    """
    buf = StringIO()
    sites = _detected_call_sites(result)

    buf.write("# gate.yaml — generated by diplomat-agent\n")
    buf.write("#\n")
    buf.write("# Produced automatically from a scan. Review before relying on it:\n")
    buf.write("# generated policies default to on_fail: REVIEW so nothing breaks on the\n")
    buf.write("# first run — switch a policy to on_fail: STOP once you've confirmed its\n")
    buf.write("# parameters (max_amount, blocked domains, ...) are right for you.\n")
    buf.write("#\n")

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    buf.write(f'# generated: "{now}"\n')
    buf.write(f'# agent_version: "{__version__}"\n')
    buf.write(f'# scanned_path: "{scanned_path}"\n')
    buf.write('# spec_version: "1.0"\n')
    buf.write("\n")

    implemented = sorted(
        c for c in sites if (fam := GATE_FAMILY_MAP.get(c)) and fam.family is not None
    )
    unimplemented = sorted(
        c for c in sites if (fam := GATE_FAMILY_MAP.get(c)) and fam.family is None
    )

    if not implemented:
        buf.write("# No detected side effect has an implemented diplomat-gate policy\n")
        buf.write("# family yet — nothing to actively protect from this scan.\n")
        buf.write("policies: []\n")
    else:
        buf.write("policies:\n")
        for category in implemented:
            family = GATE_FAMILY_MAP[category]
            buf.write(
                f"  # {len(sites[category])} {category} call site(s) detected "
                f"— {family.family} family\n"
            )
            for policy_id in family.suggested:
                buf.write(f"  - id: {policy_id}\n")
                buf.write("    on_fail: REVIEW  # generated default — adjust, then consider STOP\n")

    if unimplemented:
        buf.write("\n# --- Detected, but no diplomat-gate policy family exists yet ---\n")
        for category in unimplemented:
            family = GATE_FAMILY_MAP[category]
            call_sites = sites[category]
            buf.write(f"#\n# {len(call_sites)} {category} call site(s) detected:\n")
            for file, line, name in call_sites[:_MAX_CALL_SITES_SHOWN]:
                buf.write(f"#   {file}:{line} ({name})\n")
            remaining = len(call_sites) - _MAX_CALL_SITES_SHOWN
            if remaining > 0:
                buf.write(f"#   ... and {remaining} more\n")
            if family.issue is not None:
                buf.write(
                    "# No policy family available yet — tracked in "
                    f"https://github.com/Diplomat-ai/diplomat-gate/issues/{family.issue}\n"
                )

    content = buf.getvalue()
    Path(output_path).write_text(content, encoding="utf-8")
    return content
